sudo: false
language: node_js
node_js:
- '10'
cache:
  directories:
  - "$HOME/.npm"
branches:
  only:
  - master
  - "/^v\\d+\\./"
script: yarn build
deploy:
  skip_cleanup: true
  provider: npm
  email: editied@gmail.com
  api_key: "$NPM_TOKEN"
  on:
    tags: false
    repo: edtoken/clean-vuecli3-package
